services:
  - type: web
    name: nova-bank-api
    runtime: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: nova-bank-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: nova-bank-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: nova-bank-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: nova-bank-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: nova-bank-db
          property: password
      - key: SECURITY_JWT_EXPIRATION_MS
        value: "86400000"
      - key: SECURITY_JWT_SECRET
        sync: false

databases:
  - name: nova-bank-db
    plan: free
    databaseName: nova_bank
    user: nova_user
