spring:
  application:
    name: nova-bank-core

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:nova_bank}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:postgres}}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    show-sql: false

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env,threaddump,heapdump
  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}
    expiration-ms: ${SECURITY_JWT_EXPIRATION_MS:86400000}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

app:
  bootstrap:
    historical:
      enabled: false
      months: 3
      users: 3
      tx-per-week: 6
  notifications:
    webhook:
      enabled: false
      url: ""
      api-key: ""
      connect-timeout-ms: 2000
      read-timeout-ms: 3000
